### ISSUE TITLE
AttributeError: 'TrainProcess' object has no attribute 'plugins'

### ISSUE THREAD

**Issue by duzhenjiang113** [SymenYang/CPCGAN#2]
```
Traceback (most recent call last):
  File "/home/xiaodu/anaconda3/envs/CPCGAN/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xiaodu/anaconda3/envs/CPCGAN/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xiaodu/anaconda3/envs/CPCGAN/lib/python3.6/site-packages/DLNest-0.3.1-py3.6.egg/DLNest/Run.py", line 56, in <module>
    runTrain(args)
  File "/home/xiaodu/anaconda3/envs/CPCGAN/lib/python3.6/site-packages/DLNest-0.3.1-py3.6.egg/DLNest/Run.py", line 46, in runTrain
    showOnScreen = args.ss
  File "/home/xiaodu/anaconda3/envs/CPCGAN/lib/python3.6/site-packages/DLNest-0.3.1-py3.6.egg/DLNest/Operations/RunIndependent.py", line 25, in runIndependent
    TProcess.run()
  File "/home/xiaodu/anaconda3/envs/CPCGAN/lib/python3.6/site-packages/DLNest-0.3.1-py3.6.egg/DLNest/Executor/TaskProcess.py", line 258, in run
    if self.initModules() != "Skip":
  File "/home/xiaodu/anaconda3/envs/CPCGAN/lib/python3.6/site-packages/DLNest-0.3.1-py3.6.egg/DLNest/Executor/TaskProcess.py", line 222, in initModules
    self.__initLifeCycle(rank = rank)
  File "/home/xiaodu/anaconda3/envs/CPCGAN/lib/python3.6/site-packages/DLNest-0.3.1-py3.6.egg/DLNest/Executor/TaskProcess.py", line 52, in __initLifeCycle
    self.lifeCycle = self.lifeCycleModule.__getattribute__(lifeCycleName)(taskProcess = self,rank = rank, plugins = self.plugins)

AttributeError: 'TrainProcess' object has no attribute 'plugins'
```

Could you please tell me how to deal with it?

**Comment by SymenYang** [comment]
It is a bug from an update of DLNest. We have fixed it in the newest version. You can also fix it by adding one line after line 30 of `DLNest/Executor/TaskProcess.py` and reinstalling DLNest:
```python
...

class TaskProcess(Process):
    def __init__(self,task : TaskInformation):
        super(TaskProcess,self).__init__()
        self.task = task
        self.finishedEpoch = -1
        self.rank = -1
        self.worldSize = -1
        self.plugins = [] # Add this line
...
```
We are sorry for our mistakes.

**Comment by duzhenjiang113** [comment]
Thanks for your reply, i also meet another issue:
```
Traceback (most recent call last):
  File "/home/xiaodu/anaconda3/envs/CPCGAN/lib/python3.6/site-packages/DLNest-0.3.1-py3.6.egg/DLNest/Executor/TrainProcess.py", line 114, in mainLoop
    self.__train_an_epoch(nowEpoch)
  File "/home/xiaodu/anaconda3/envs/CPCGAN/lib/python3.6/site-packages/DLNest-0.3.1-py3.6.egg/DLNest/Executor/TrainProcess.py", line 77, in __train_an_epoch
    self.runner._runOneStep(data,self.logDict,_iter,nowEpoch)
  File "/home/xiaodu/anaconda3/envs/CPCGAN/lib/python3.6/site-packages/DLNest-0.3.1-py3.6.egg/DLNest/Plugins/Utils/CheckPlugins.py", line 14, in checkAndRun
    return func(*args, **kwargs)
  File "/home/xiaodu/anaconda3/envs/CPCGAN/lib/python3.6/site-packages/DLNest-0.3.1-py3.6.egg/DLNest/Common/RunnerBase.py", line 64, in _runOneStep
    return self.runOneStep(data = data, log = log, iter = iter, epoch = epoch)
  File "/home/xiaodu/CPCGAN/Saves/2021-12-25_15-34-03_119/Model/CPCGAN.py", line 169, in runOneStep
    self.pre_train(data,log)
  File "/home/xiaodu/CPCGAN/Saves/2021-12-25_15-34-03_119/Model/CPCGAN.py", line 106, in pre_train
    f_pc_1 = self.Net_1(pc_0,expanded_z)
  File "/home/xiaodu/anaconda3/envs/CPCGAN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xiaodu/CPCGAN/Saves/2021-12-25_15-34-03_119/Model/Subnets.py", line 104, in forward
    f_0 = self.linear_pc(pc)
  File "/home/xiaodu/anaconda3/envs/CPCGAN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xiaodu/anaconda3/envs/CPCGAN/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/xiaodu/anaconda3/envs/CPCGAN/lib/python3.6/site-packages/torch/nn/functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: Tensor for 'out' is on CPU, Tensor for argument #1 'self' is on CPU, but expected them to be on GPU (while checking arguments for addmm)
```

**Comment by duzhenjiang113** [comment]
I also meet some problems in CPCGAN.py:
```
def pre_train(self,data,log):
        pc_1,pc_0 = data
        pc_1 = pc_1
        pc_0 = pc_0
```
I think it should be changed as :
```
def pre_train(self,data,log):
        pc_1,pc_0 = data
        pc_1 = pc_1.cuda()
        pc_0 = pc_0.cuda()
```

**Comment by SymenYang** [comment]
> I also meet some problems in CPCGAN.py:
> 
> ```
> def pre_train(self,data,log):
>         pc_1,pc_0 = data
>         pc_1 = pc_1
>         pc_0 = pc_0
> ```
> 
> I think it should be changed as :
> 
> ```
> def pre_train(self,data,log):
>         pc_1,pc_0 = data
>         pc_1 = pc_1.cuda()
>         pc_0 = pc_0.cuda()
> ```

We have fixed the bug of not moving data in a tuple to the correct device in the newest version of DLNest. We are sorry for our mistakes.
